apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: cncf-demo
data:
  BG_COLOR: "#87ceeb"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        image: nginx:alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ns-internal
  namespace: cncf-demo
spec:
  podSelector:
    matchLabels:
      app: demo-app
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress