apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cncf-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaruwat-panturat/pacman-for-k8s.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: cncf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true