apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: argocd
spec:
  destination:
    namespace: pacman
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: .
    repoURL: https://github.com/jaruwat-panturat/pacman-for-k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true