apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-managed-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaruwat-panturat/k8s-lab.git
    targetRevision: main
    path: crossplane/managedResources
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true