apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-issue-6104
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaruwat-panturat/k8s-lab.git
    targetRevision: main
    path: eso
  destination:
    server: https://kubernetes.default.svc
    namespace: eso-issue-6104
  syncPolicy: {}
