apiVersion: v1
kind: Namespace
metadata:
  name: eso-issue-6104

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  namespace: eso-issue-6104
spec:
  provider:
    fake:
      data:
      - key: /my/config
        value: '{"host":"localhost","port":"5432","db":"mydb"}'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-configmap-es
  namespace: eso-issue-6104
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: my-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
  dataFrom:
  - extract:
      key: /my/config
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store-secret
  namespace: eso-issue-6104
spec:
  provider:
    fake:
      data:
      - key: /my/credentials
        value: '{"username":"admin","password":"s3cr3t"}'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-secret-es
  namespace: eso-issue-6104
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: fake-store-secret
    kind: SecretStore
  target:
    name: my-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /my/credentials

